spring:
  datasource:
    url: jdbc:h2:mem:kotlin_spring_boot_db
    username: keilla
    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false